service: ${env:NAME}
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  timeout: 90
  runtime: nodejs14.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  versionFunctions: false
package:
  individually: true
custom:
  serverless-offline:
    apiKey: '0123456789'
    httpPort: 3000
  urlPrefix: 'sls'
  webpack:
    includeModules: true
    excludeFiles: ./**/*.test.js
functions: ${file(./resources/lambda/functions.yml)}
resources:
  - ${file(./resources/config/iam.yml)}
